include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    close_sinks: true
    sort_constructors_first: false
    avoid_classes_with_only_static_members: false

